### PR TITLE
Change challenge where-art-though name to match English fcc one

### PR DESCRIPTION
**Pull request by wudifeixue**
In this PR:

Fix issue #232 

Do note I am a bit afraid that this change would break the whole project.  
But this is all the sources I can find for the changes I have to make.

### CODE REVIEW

**Comment by S1ngS1ng** [comment]
@wudifeixue Did you run it on local server? I am wondering if it covers the `Map` panel.

**Comment by wudifeixue** [comment]
## First off I just did a test on this and it works great. 

image  

Well, I run ```node seed``` and everything works great.  
Then I can start the project with ```gulp``` too without a problem.  (I already used ```mongod```)  

## Here is the problem
- I can not open these two locally.
image

I also tried to ```npm test``` this, then it did not pass.  
```bash
  Failed Tests: There was 1 failure

    Friendly Date Ranges


      ✖ TypeError: assert.isNotArray is not a function


  total:     729
  passing:   728
  failing:   1
  duration:  7s



npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test-challenges"
npm ERR! node v6.9.5
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freecodecamp.cn@0.1.0 test-challenges: `babel-node seed/test-challenges.js | tap-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freecodecamp.cn@0.1.0 test-challenges script 'babel-node seed/test-challenges.js | tap-spec'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freecodecamp.cn package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node seed/test-challenges.js | tap-spec
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freecodecamp.cn
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freecodecamp.cn
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Curtis/.npm/_logs/2017-08-01T20_30_00_562Z-debug.log
npm ERR! Test failed.  See above for more details.

```
[2017-08-01T20_30_00_562Z-debug.log](https://github.com/FreeCodeCampChina/freecodecamp.cn/files/1191863/2017-08-01T20_30_00_562Z-debug.txt)

After upgrade node and npm as well I experienced the same problem, it seems like PR #248 with ```assert.isNotArray``` is causing some trouble.

**Comment by S1ngS1ng** [comment]
@wudifeixue Will take a look today.

**Comment by wudifeixue** [comment]
This one should be good too now since test is fixed, though how come I can't open chat or course list locally?

**Comment by S1ngS1ng** [comment]
@wudifeixue Not sure :man_facepalming: . Are these rendered from server side? I guess...

**Comment by wudifeixue** [comment]
Have you tested them out locally?

**Comment by S1ngS1ng** [comment]
@wudifeixue 
Yep. Works fine on my side. Thanks!
image

**Review by S1ngS1ng — APPROVED** [review]
👍 LGTM

**Pull request merged**
