### PR TITLE
chore(translation) Update translation for advanced-bonfires

### PR DESCRIPTION
**Pull request by S1ngS1ng**
### In this PR:
- Add translation of advanced-bonfires

### CODE REVIEW

**Comment by S1ngS1ng** [comment]
@wudifeixue Lemme know if I missed something. Looks like this file doesn't require lots of translation.

**Review by S1ngS1ng — COMMENTED** [review]
@wudifeixue Lemme know if I missed something. Looks like this file doesn't require lots of translation.

**Review by wudifeixue — COMMENTED** [review]
感觉原题的幽默感没必要删掉？

**Comment by S1ngS1ng** [comment]
@wudifeixue 我怕强行翻译造成误会😂所以就把那句删掉了。。新的 PR 也一样。。不过新 PR 里我改成了 `请把你的代码写在这里`

**Pull request merged**
